__title__ = "vacheck"
__description__ = "Verbal autopsy Data consistency checks (from InterVA Algorithm)."
__url__ = "https://github.com/verbal-autopsy-software/vacheck"
__version__ = "0.0.1"
__author__ = "Jason Thomas"
__author_email__ = "jarathomas@gmail.com"
__license__ = "GPLv3"
